name: Sync with GWDG GitLab

on: [push]

jobs:
  build:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: "https://gitlab.gwdg.de/GAUMI-fginfo/sit-website.git"
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
